---
--- Generated by Luanalysis
--- Created by liuqin.
--- DateTime: 2020/10/13 下午7:33
---
local session = {
    _VERSION = "3.6"
}

session.__index = session

function session.new(opts)
    if getmetatable(opts) == session then
        return opts
    end

end


return session