---
--- Generated by Luanalysis
--- Created by liuqin.
--- DateTime: 2020/10/13 下午5:45
---
local core        = require("apisix.core")
local plugin_name = "session-auth"
local schema = {
    type = "object",
    properties = {
        --加密字符串
        secret={type="string",minLength=1,},
        --前缀
        name = {type="string",minimum = 1, default = "session_id"},
        --session过期事件
        expire = {type = "integer", minimum = 1,default = 3600},
        --redis请求超时事件
        timeout = {
            type = "integer", minimum = 1,
            default = 1000,
        },
        storage = {
            type = "string",
            enum = {"redis", "memcache"},
            default = "redis",
        },
        password = {type="string",minLength = 0,},
    },
    required = {"name","expire","timeout","storage"},
    dependencies = {
        storage = {
            oneOf = {
                {
                    properties = {
                        storage = {
                            enum = {"redis"},
                        },
                        hosts = {
                            type = "array",
                            items = {
                                type = "object",
                                properties = {
                                    ip = {type="string"},
                                    port = {type = "integer",minimum = 1, default = 6379,}
                                },
                                required = {"ip","port"},
                            },
                            minItems = 1
                        }
                    },
                    required = {"mode"},
                },
                {
                    properties = {
                        storage = {
                            enum = {"memcache"},
                        },
                        host = {
                            type = "object",
                            properties = {
                                ip = {type="string"},
                                port = {type = "integer",minimum = 1, default = 6379,}
                            },
                            required = {"ip","port"},
                        },
                    },
                },
            }
        }
    }
}
local _M = {
    version  = 0.1,
    priority = 3200,
    type = 'auth',
    name     = plugin_name,
    schema   = schema,
}
function _M.check_schema(conf)
    local ok, err = core.schema.check(schema, conf)
    if not ok then
        return false, err
    end
    return true
end

do
    function _M.rewrite(conf, ctx)
        core.log.error(core.json.encode(ngx.var))
    end
end  -- do
return _M